### ISSUE TITLE
Demo triggers magnifier while dragging on iPad Chrome or Safari

### ISSUE THREAD

**Issue by bebraw** [yahoo/react-dnd-touch-backend#1]
If you try to drag at the demo on iPad Chrome (iPad Air 2, newest Chrome) or Safari, it seems to trigger magnifier. I think you might need to apply some meta tags and/or CSS trickery to get rid of that. I recall it's somehow related to text selection (default behavior).

**Comment by longlho** [comment]
cool I'll take a look asap.

**Comment by bebraw** [comment]
It's better now. I tested the new implementation and noticed the following things:

* iPad Chrome - If I change the list order quickly, everything works as expected. If I hold a finger on an item for a while and drag after that, the magnifier appears at the browser address bar. Maybe this triggers some behavior we're missing in the code?
* iPad Safari - I cannot get the magnifier to show up here. There's one issue, though. If you drag an item to the right, it will start to scale the view while dragging. The further right you drag, the smaller the list becomes. This is something I don't see in Chrome.

**Comment by longlho** [comment]
Yeah touch events get complicated in those cases and is sensitive to its children. Long tap does bring up the context menu in some browsers, also if the children is an `<a>`, long tap triggers `Add to Bookmarks` and all that stuff. I don't intend to `preventDefault` or `stopPropagation` to those behaviors cause it'll cause side effects.

Issue 2 should be fixed in #54acf4f485cc658e97074b62bb2e24a4b8742ec2

**Comment by bebraw** [comment]
Ok, cool. Thanks!
