### ISSUE TITLE
Chrome/Android are blocking the preventDefault of document level touch event listeners

### ISSUE THREAD

**Issue by jsg2021** [yahoo/react-dnd-touch-backend#44]
https://www.chromestatus.com/features/5093566007214080
![screen shot 2016-12-13 at 11 49 39 am](https://cloud.githubusercontent.com/assets/577453/21152015/40f93eae-c12a-11e6-8319-b1af7e0714d6.png)

**Comment by longlho** [comment]
tks I'll take a look but feel free to PR :)

**Comment by dhenson02** [comment]
@longlho any chance you'd be able to publish a version increment for this to NPM?

**Comment by longlho** [comment]
@dhenson02 `0.3.4` published :)

**Comment by RByers** [comment]
Sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  The better fix for scroll performance is to add an appropriate `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), as you would need to in order to use pointer events (eg. to support touch in Microsoft Edge/IE).

**Comment by longlho** [comment]
@RByers gotcha tks
