### ISSUE TITLE
Server side compilation is broken

### ISSUE THREAD

**Issue by xavibonell** [yahoo/react-dnd-touch-backend#62]
Hi, first of all thank you for this amazing repository, it's been very useful so far, but something changed over the last month and now it won't compile anymore on a webpack-babel environment. 
I had to fork the repo and fix it manually, the problem exists on the polyfill implementation for document.elementsFromPoint and the assumption that 'document' is an existing variable. Even though your last commit was regarding this very issue, I'm afraid `document && document.elementsFromPoint` is not defensive enough, it would brake on a server side compilation since it doesn't exist there.

Thank you again!

**Comment by JoaoMosmann** [comment]
Are you doing unit tests with `react-dnd-touch-backend` ?

**Comment by JoaoMosmann** [comment]
If you're doing unit tests, you should be using the [TestBackend](http://react-dnd.github.io/react-dnd/docs-testing.html)

If it's not the case, why are you loading it in the backend?

**Comment by xavibonell** [comment]
Hi Joao, thank you very much for your answer! Is an isomorphic app. So views that require touch events will have to import that backend in either environments. Anyway the problem happens when the whole bundle.js is packed and compiled through webpack+babel and that happens on the backend. Is there any reason to assume the existence of 'document'? 
I moved the polyfill inside the class in order to be able to check it. Don't know if is the best solution but it works. I'm actually surprised to be the only one who has noticed that, since react+redux+webpack+babel seems to be almost a standard nowadays.

Thanks again for your time.

**Comment by JoaoMosmann** [comment]
To be honest, I've never done an isomorphic app that had react-dnd. But surely this is the problem.  This was my mistake, you can see throughout the code, there are conditions like `typeof window === 'undefined'` to prevent the code from running in the backend, but they're all inside the class.

I did it outside the class to follow the same pattern, all the "helper" functions are outside, like `getEventClientTouchOffset `,  `getEventClientOffset ` and `supportsPassive`. And also because it's a polyfill.

I think chaging the condition `(document && document.elementsFromPoint)` to `(typeof document !== 'undefined' && document.elementsFromPoint)` might do the job.

You can also move it to the Class as you did. But first, try changing the condition to keep the pattern and see if it works. 

Do a PR and I'll test it in here.

Cheers :smile:

**Comment by remcotak** [comment]
I'm having the same issue, looking forward to the solution

**Comment by achtan** [comment]
there is still the same error on https://github.com/yahoo/react-dnd-touch-backend/blob/1381dbc56a4e4bf0efdd6e5641850f7439ff3591/src/Touch.js#L52

````
ReferenceError: document is not defined
W20170526-15:45:11.608(2)? (STDERR)     at Object.<anonymous> (.../node_modules/react-dnd-touch-backend/dist/Touch.js:72:9)
````

**Comment by JoaoMosmann** [comment]
Hi @achtan. Thanks for the reporting.

There is already a PR coming in #69 

I'll only be able to fix it later. If you want, you can fix the PR, or do one yourself and I'll merge it.
